# Generated by Django 4.0.5 on 2022-07-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_brand_alter_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
