# Generated by Django 4.0.6 on 2022-08-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='discounted_price',
        ),
    ]
