# Generated by Django 4.0.6 on 2022-08-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_discount_price_product_discounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='discount_price',
        ),
    ]
